# name: Build & Deploy

# on:
#   push:
#     branches:
#       - develop
# jobs:
#   build-and-deploy:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout
#       uses: actions/checkout@v1
#     - uses: actions/setup-node@v1 # install node and npm
#       with:
#         node-version: '10.x'
#     - uses: actions/cache@v1 # utilize cache
#       with:
#         path: ~/.npm
#         key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
#         restore-keys: |
#           ${{ runner.os }}-node-
#     ## Build Step            
#     - name: Build 
#       run: |
#         npm install
#         npm install -g @angular/cli
#         npm install -g angular-cli-ghpages
#         ng build --prod=true --outputPath=docs
#     ## Deploy Step
#     - name: Deploy
#       env:
#         ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#       run: ng deploy --no-silent







name: Build and Deploy
on:
  push:
    branches:
      - develop
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/setup-node@v1 # install node and npm
      with:
        node-version: '10.x'
    - uses: actions/cache@v1 # utilize cache
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    steps:
    - uses: actions/checkout@v2
    - name: All things angular
      uses: ./AhsanAyaz/angular-deploy-gh-pages-actions
      with:
        github_access_token: ${{ secrets.ACCESS_TOKEN }}
        angular_dist_build_folder: docs/